import '../globals.css'
import { Poppins } from "next/font/google";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
const poppins = Poppins({
  subsets: ['latin'], // Specify the subset for the font
  weight: ['400', '500', '700'], // Add the font weights you want to use
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
